[book]
authors = ["zjp <jiping_zhou@foxmail.com>"]
language = "zh"
multilingual = false
src = "src"
title = "开源操作系统训练营笔记"

[preprocessor.theme]
pagetoc = true
sidebar-width = "270px"

pagetoc-width = "15%"
content-max-width = "78%"
content-main-margin-left = "5%"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/zjp-CN/os-notes"
edit-url-template = "https://github.com/zjp-CN/os-notes/edit/main/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

# Michael-F-Bryan/mdbook-linkcheck
[output.linkcheck]

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false

[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"
